Add Hive Server2 Dockerfile
- Occurs error on running
- Still on working to resolve issue :
```
org.apache.hadoop.hive.metastore.HiveMetaException: Failed to get schema version.
Underlying cause: java.sql.SQLException : Conflicting create attributes specified.
SQL Error code: 40000
org.apache.hadoop.hive.metastore.HiveMetaException: Failed to get schema version.
```